# Generated by Django 2.2 on 2021-12-02 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.BigIntegerField()),
                ('anno', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apps.secretaria.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.secretaria.Empresa')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.secretaria.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=500)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.secretaria.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.BigIntegerField()),
                ('departamento', models.CharField(max_length=100)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.secretaria.Facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluacion', models.CharField(max_length=500)),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fechaReunion', models.DateTimeField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.secretaria.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.secretaria.Facultad'),
        ),
    ]
