# Generated by Django 2.2 on 2021-12-02 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_tribunaltesistutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRibunalTesisOponente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.secretaria.Profesor')),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.secretaria.Tesis')),
            ],
        ),
    ]
